version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
    - build_x86
    - build_m1
jobs:
  build_x86:
    docker:
      - image: cimg/base:2024.09
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Place example data sets in the home directory
          command: cp -r example-data-sets/* ~/
      - run:
          name: Install prerequisites
          command: scripts/install-prerequisites.sh
      - run:
          name: Install GraphBLAS (using compact mode to reduce build times)
          command: scripts/install-graphblas.sh --compact
      - run:
          name: Install LAGraph
          command: scripts/install-lagraph.sh
      - run:
          name: Initialize benchmark package
          command: scripts/init.sh
      - run:
          name: Perform benchmark test run
          command: |
            . scripts/project-vars.sh
            cd ${PROJECT}
            bin/sh/run-benchmark.sh
            grep -F 'In total, [24 / 24] benchmark(s) succeed.' report/*/log/benchmark-full.log
      - slack/status
  build_m1:
    macos:
      xcode: 15.4.0
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - run:
          name: Place example data sets in the home directory
          command: cp -r example-data-sets/* ~/
      - run:
          name: Install prerequisites
          command: |
            scripts/install-prerequisites.sh
            curl -O https://mac.r-project.org/openmp/openmp-16.0.4-darwin20-Release.tar.gz
            sudo tar fvxz openmp-16.0.4-darwin20-Release.tar.gz -C /
      - run:
          name: Install GraphBLAS (using compact mode to reduce build times)
          command: scripts/install-graphblas.sh --compact
      - run:
          name: Install LAGraph
          command: scripts/install-lagraph.sh
      - run:
          name: Initialize benchmark package
          command: scripts/init.sh
      - run:
          name: Perform benchmark test run
          command: |
            . scripts/project-vars.sh
            cd ${PROJECT}
            bin/sh/run-benchmark.sh
            grep -F 'In total, [24 / 24] benchmark(s) succeed.' report/*/log/benchmark-full.log
      - slack/status
