version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
    - build
jobs:
  build:
    docker:
      - image: cimg/base:2023.02-22.04
    resource_class: xlarge
    steps:
      - checkout
      - run: sudo apt update && sudo apt install cmake g++ maven
      - run: cp -r example-data-sets/* ~/
      - run: bin/sh/install-dependencies.sh
      - run: |
          # GraphBLAS
          git clone --depth 1 --branch v7.4.3 --single-branch https://github.com/DrTimothyAldenDavis/GraphBLAS
          cd GraphBLAS
          cd build
          # make build quicker by disabling the generation of functions for each individual type
          cmake .. -DCMAKE_C_FLAGS="-DGBCUDA_DEV=1"
          make -j$(nproc)
          sudo make install
          sudo ldconfig
          cd ../..
      - run: |
          # LAGraph
          git clone --depth 1 --branch pagerank-graphalytics-variant --single-branch https://github.com/GraphBLAS/LAGraph
          cd LAGraph
          JOBS=$(nproc) make
          sudo make install
          sudo ldconfig
          cd ..
      - run: |
          # init
          ./init.sh
      - run: |
          # run
          cd graphalytics-1.6.0-SNAPSHOT-graphblas-0.1-SNAPSHOT/
          bin/sh/run-benchmark.sh
      - slack/status
